# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qiq4ysdar955htxpn3XjVzbAD0wC3FWN
"""

#En esta parte del código se inicializa un diccionario llamado calificaciones con dos claves y sus respectivos valores la clave 'nombre' tiene el valor 'Sandra', y la clave 'notafinal' tiene el valor 5.0
calificaciones = {
    'nombre': 'Sandra',
    'notafinal': 5.0
}
#En esta parte del código, el diccionario calificaciones se reinicializa con diferentes claves y valores ahora las claves son los nombres de los estudiantes ('Sandra', 'Adriana', 'Mauricio' y 'Jose') y los valores son las calificaciones correspondientes (5.0, 5.0, 4.5 y 2.5 respectivamente).
calificaciones = {
    'Sandra': 5.0,
    'Adriana': 5.0,
    'Mauricio': 4.5,
    'Jose': 2.5
}
#En esta parte, se utiliza un bucle for para iterar sobre los elementos del diccionario calificaciones, calificaciones.items() devuelve pares clave-valor del diccionario dentro del bucle, i representa la clave (nombre del estudiante) y j representa el valor (calificación del estudiante).
for i, j in calificaciones.items():
    print(i, j)